version : 0.0.2
container-name-run : "demoxxx"
container-name-tools : "bx-dev-demoxxx-tools"
image-name-run : "demoxxx"

image-name-tools : "bx-dev-java-maven-tools"
host-path-run : "target"
build-cmd-run : "mvn install -Dmaven.repo.local=/project/.m2/repository"
test-cmd : "mvn install -Dmaven.repo.local=/project/.m2/repository"
build-cmd-debug : "mvn install -Dmaven.repo.local=/project/.m2/repository"

container-path-run : "/project"
container-path-tools : "/project"

container-port-map : "9080:9080,9443:9443"
container-port-map-debug : "7777:7777"

dockerfile-run : "Dockerfile"
dockerfile-tools : "Dockerfile-tools"

debug-cmd : "server debug"
ibm-generated-id : "7a723dc0-8ec8-4132-bd59-b84a8fda24b6"
credentials-filepath : "src/main/liberty/config/server.env, log.txt"